### ISSUE TITLE
"singlefilenames" is  not a file 

### ISSUE THREAD

**Issue by Adarsh-achu** [85pando/mcStats#12]
python mcStats.py --help
  File "/data/data/com.termux/files/home/Bot/mcStats/mcStats.py", line 127
    print singlefile_names, 'is not a file'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(singlefile_names, 'is not a file')?

**Comment by Gjum** [comment]
You can try running this with python 2.7 which allows this old `print` syntax.

**Comment by Adarsh-achu** [comment]
$ python2 mcStats.py --help
Traceback (most recent call last):
  File "mcStats.py", line 31, in <module>
    from pystache import Renderer
ImportError: No module named pystache

**Comment by Gjum** [comment]
you will have to install all modules for python 2 again of course. anyway this seems to not be a bug with this mcstats library

**Comment by Adarsh-achu** [comment]
how to do that i have python 2
